# 行列演算の基礎

In [3]:
import numpy as np

#ベクトルの定義
x = np.array([[1],[2],[3]])

#行列の定義
X = np.array([[1,2],[3,4]])

#転置
Xt = X.T

#逆行列
X_inv = np.linalg.inv(X)

#行列積
XX_inv = np.dot(X,X_inv)

# よくある間違い

In [5]:
#転置のやり方
a = np.array([1,2,3])
a = a.T
b = np.array([[1,2,3]])
b = b.T
print(a)
print(b)

[1 2 3]
[[1]
 [2]
 [3]]


# Numpyでよく使う処理


In [9]:
#行と列の数
row,col = X.shape
print(row+col)
for x in X:
    print(x)
    print('--')

4
[1 2]
--
[3 4]
--


# 演習

In [17]:
X = np.array([[1,2,3],
             [1,2,5],
              [1,3,4],
              [1,5,9]
             ])
Y = np.array([
    [1],
    [5],
    [6],
    [8]
])

Xt = X.T
XtX = np.dot(Xt,X)
XtX_inv = np.linalg.inv(XtX)


XtY = np.dot(Xt,Y)
w = np.dot(XtX_inv,XtY)
w

array([[-0.14285714],
       [ 0.71428571],
       [ 0.57142857]])

# Scikit-learnで実装


In [21]:
import sklearn
from sklearn.linear_model import LinearRegression

#モデルの宣言
model = LinearRegression()

#モデルの学習←パラメータの調整
model.fit(X,Y)

#調整後のパラメータ
model.coef_

#予測精度←決定係数
model.score(X,Y)

0.6923076923076925